INSERT INTO users (login, password, email, primaryWeapon, backupWeapon, groupMember, created, active) VALUES ("Janek", "$2a$10$wWh7p81HHTDgAurUosNBOuJS/H82OvdjG0gAQsOosOJz2ogonmnyi", "janek.kos@wp.pl", "ASSAULT", "ASSAULT", "PRETORIANS", "2005-04-12 21:12:43", true);
INSERT INTO User_priviliges (User_id, priviliges) VALUES (1, "ADMINISTRATOR")

INSERT INTO users (login, password, email, primaryWeapon, backupWeapon, groupMember, created, active) VALUES ("Szoni", "$2a$10$wWh7p81HHTDgAurUosNBOuJS/H82OvdjG0gAQsOosOJz2ogonmnyi", "szoni.tank@wp.pl", "ASSAULT", "ASSAULT", "PRETORIANS", "2005-05-10 12:08:11", true);
INSERT INTO User_priviliges (User_id, priviliges) VALUES (2, "ORGANISATOR")
INSERT INTO users (login, password, email, primaryWeapon, backupWeapon, groupMember, created, active) VALUES ("Medyk", "$2a$10$wWh7p81HHTDgAurUosNBOuJS/H82OvdjG0gAQsOosOJz2ogonmnyi", "medyk.dentysta@wp.pl", "ASSAULT", "SUPPORT", "PRETORIANS", "2001-11-02 08:09:00", true);
INSERT INTO User_priviliges (User_id, priviliges) VALUES (3, "ORGANISATOR")

INSERT INTO users (login, password, email, primaryWeapon, backupWeapon, groupMember, created, active) VALUES ("Pabieda", "$2a$10$wWh7p81HHTDgAurUosNBOuJS/H82OvdjG0gAQsOosOJz2ogonmnyi", "luska@wp.pl", "ASSAULT", "SUPPORT", "OSA", "2012-06-30 17:35:21", true);
INSERT INTO User_priviliges (User_id, priviliges) VALUES (4, "USER")
INSERT INTO users (login, password, email, primaryWeapon, backupWeapon, groupMember, created, active) VALUES ("Milus", "$2a$10$wWh7p81HHTDgAurUosNBOuJS/H82OvdjG0gAQsOosOJz2ogonmnyi", "milus@wp.pl", "SUPPORT", "ASSAULT", "ASGWawa", "2012-05-27 18:30:37", true);
INSERT INTO User_priviliges (User_id, priviliges) VALUES (5, "USER")
INSERT INTO users (login, password, email, primaryWeapon, backupWeapon, groupMember, created, active) VALUES ("SPAJDA", "$2a$10$wWh7p81HHTDgAurUosNBOuJS/H82OvdjG0gAQsOosOJz2ogonmnyi", "SPAIDA@wp.pl", "SNIPER", "SUPPORT", "OSA", "2012-06-30 17:35:21", true);
INSERT INTO User_priviliges (User_id, priviliges) VALUES (6, "USER")

INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-12 21:12:43", "Tru, tru. Co to za gniot?! Pliki muszą wyjść dzisiaj, nadszedł czas na mini brejnstorm, dlatego nie musi to być ASAP. Na to wygląda, że znowu zmienili hasła do drukarek, a Pamela jest na urlopie, także musimy ich zacząć ścigać. Na szczęście mamy wszystkie konieczne apruwale, także klient będzie usytasy. Fakap na całej linii: serwer się zaciął, więc nie ma się co śmiać - nie ma opierdalania się!", "1");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-12 21:13:43", "Jestem dobrym kołczem dla was. Tak myślę, że nie potraficie ogarnąć nawet najprostszego fakapu, więc obcinam wam pensje do czasu poprawy sytuacji. Może poczekamy jeszcze trochę na wypłaty. Zrób coś lepszego. Ciężka sprawa, bo kołczing to coś, czego wam trzeba, także znowu będzie FAKAP. Nie podoba mi się.", "1");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-12 21:14:43", "Niestety zredżektowali nam te zmiany, ale co tam – nie płacą nam za nadgodziny. Tak czy inaczej, mamy kola z biznesem o 15:00. To będzie wyzwanie, bo klient przesunął dedlajn na wczoraj, także trzeba dobrze stargetować ten kejs. Dizajn musi urywać dupę, ale to będzie lekkie jak czilałt w sobotę, więc idziemy na mały korytarzowy fokus. Obczaj, że mamy wszystkie konieczne apruwale, więc sprawa jest jasna: klient będzie usytasy.", "1");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-12 21:15:43", "Gud dżob! Może nie będzie premii. Ciężka sprawa, bo kołczing to coś, czego wam trzeba, więc do roboty.", "1");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-14 21:16:43", "Fakapik jakiś znowu? Podobno mejle znowu padły, ale co tam – nie płacą nam za nadgodziny. Tak czy inaczej, to musi być ASAP. Mam dla ciebie czelendż: wyłącz te głupie gify z kotami, ale jak coś to wiesz, może helpdesk ci pomoże. Dedlajn najlepszą inspiracją, nie?", "1");

INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-13 21:12:43","Niestety padły serwery, ale co tam – nie płacą nam za nadgodziny. Tak czy inaczej, miting działowy będzie za godzinę. Generalnie wszystko jest on trak, ale przed chwilą zapdejtowali gajdlajnsy, a Anita jest na urlopie, także inne taski będą musiały poczekać. Logo jest najważniejsze!", "2");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-13 21:12:55", "Nie musisz się starać, tylko zamykaj tego fejsa i siedź cicho, ale wiesz, może helpdesk ci pomoże. Wiesz, co masz robić - odpalaj kompa i nie marudź, ale wiesz, z twoim podejściem to nawet jako woźnego cię nigdzie nie zatrudnią, więc się ciesz, że masz pracę. Chodzą ploty, że trzeba to ASAP. Sam prezes zainteresował się tym projektem, a czlendż jest taki pasjonujący, także jest dobrze.", "2");

INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-13 21:12:55","Hubert ma urodziny w piątek, także mam nadzieję, że ogarnęliście jakąś zrzutę na gifta. Zabieram was na kołczing, bo klient chce to mieć ASAP, dlatego zapomnijmy na chwilę o gajdlajnsach i zróbmy to po swojemu. Najwyżej nie będzie integracji.", "3");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-14 07:44:00", "Spriperuj mi tego maila, bo kołczing to coś, czego wam trzeba, dlatego leć po mleko do kawy. Ciężka sprawa, bo ten tim nie daje sobie rady z tak prostymi czelendżami, także potrzebny będzie brejnstorm.", "3");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-15 19:18:34", "Jest nowy Pan Kanapka o 11:30. Zabieram was na kołczing, bo to będzie masakrycznie trudny czelendż, dlatego działaj keżualnie. Mamy info od koordynatora – poszedł sajnof na tym rilisie, więc sprawa jest jasna: lecimy na kawę. Obczaj, że fidback od biznesu jest pozytywny, dlatego piłeczka jest teraz po ich stronie.", "3");

INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-12 21:11:00", "Na to wygląda, że fakap był po stronie drugiego timu, więc sprawa jest jasna: klient będzie usytasy. Nadążacie? Podejść musimy do tego keżualnie. Pracujesz jeszcze w innych dizajnach? Trzeba kupić mleko do kawy. To będzie wyzwanie, bo musimy acziwnąć ten czelendż, także nie musi to być ASAP.", "4");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-14 13:00:40", "Dostałem info, że mamy wszystkie konieczne apruwale, więc o naszym timie będzie teraz głośno. Zresztą chyba czytałeś w njusleterze: będziesz lidował w tym projekcie. Czas na szybki fokus, kołczing to coś, czego wam trzeba, dlatego kawusia jest w tej chwili najimportantniejsza. Mimo, że mamy zwrotkę z testów, to fakap był po stronie drugiego timu, także piłeczka jest teraz po ich stronie.", "4");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-16 10:13:12", "Ostatecznie i tak przeniesiemy cię do innego ruma. W mailu, który Ci zaraz forwardnę, napisali, że padły serwery, więc nie ma się co śmiać - nie ma na co czekać! Jutro mamy apojtment, a nadszedł czas na mini brejnstorm, także wszystkie zaległe taski muszą być skończone przed 15:00.", "4");

INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-12 21:11:00", "Faken szit! Weź mnie dodaj do kopii. Zresztą tim lider i tak powiedział, że cofniemy ci multisporta.", "5");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-13 13:55:40", "Znowu dzieją się dziwne rzeczy… Może przeniesiemy cię do innego ruma. Ja tu jestem desyżyn mejkerem. Trzeba zrobić szybki risercz, czlendż jest taki pasjonujący, także musisz zrobić risercz. Niestety będziemy robić nowy iwent, także nie jesteśmy w stanie tego ogarnąć bez szybkiego fokusa. Mam takie dziwne wrażenie, że nawet ASAP wam nie pomoże, także macie teraz zakaz wychodzenia na kawkę w czasie mitingów.", "5");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-13 21:55:15", "Pliki muszą wyjść dzisiaj, czlendż jest taki pasjonujący, także dodaj jakieś śmieszne hasztagi. Czegoś mi tu brakuje. W mailu, który Ci zaraz forwardnę, napisali, że znowu zmienili hasła do drukarek, więc nie ma się co śmiać - mamy kola z biznesem o 15:00. Może przeniesiemy cię do innego ruma. Mamy miting, więc nie przeszkadzaj.", "5");

INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-12 21:11:00", "Mam info, że przed chwilą zapdejtowali gajdlajnsy, a Adam jest na urlopie, także szykują się nadgodziny. Czelendżowaliśmy, czelendżowaliśmy, i w końcu kros syndykacja przeszła bez zarzutu, więc sprawa jest jasna: o naszym timie będzie teraz głośno. Niestety padły serwery, a Paulina ma jutro miting w tej sprawie, więc miting działowy będzie za godzinę. Spriperuj mi tego maila, bo czlendż jest taki pasjonujący, także idziemy na mały korytarzowy fokus.", "6");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-12 21:12:40", "Łejt! I właśnie dlatego kołczing to coś, czego wam trzeba, dlatego nie musi to być ASAP. Mamy info od koordynatora – poszedł sajnof na tym rilisie, więc klient będzie usytasy. Zrób coś lepszego. Wiem, że masz już dużo na głowie, ale mejle znowu padły, a Marta ma jutro miting w tej sprawie, więc miting działowy będzie za godzinę.", "6");
INSERT INTO tweets (created, text, user_id) VALUES ("2013-04-13 12:13:12", "Zresztą tim lider i tak powiedział, że zwolnimy cały tim. Na to wygląda, że mejle znowu padły, także nie ma opierdalania się! Zabieram was na kołczing, bo kończy nam się czas, dlatego czas na multitasking! Po długich tygodniach ciężkiej pracy fiksnęliśmy wszystkie defekty, także przeniosą mnie pewnie do innego projektu. Masakra.", "6");

INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2005-04-16 23:00:00", "Łejt! I właśnie dlatego kołczing to coś, czego wam trzeba, dlatego nie musi to być ASAP. Mamy info od koordynatora – poszedł sajnof na tym rilisie, więc klient będzie usytasy. Zrób coś lepszego. Wiem, że masz już dużo na głowie, ale mejle znowu padły, a Marta ma jutro miting w tej sprawie, więc miting działowy będzie za godzinę.", "13", "1")
INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2005-04-17 20:12:43", "Jestem dobrym kołczem dla was. Tak myślę, że nie potraficie ogarnąć nawet najprostszego fakapu, więc obcinam wam pensje do czasu poprawy sytuacji. Może poczekamy jeszcze trochę na wypłaty. Zrób coś lepszego. Ciężka sprawa, bo kołczing to coś, czego wam trzeba, także znowu będzie FAKAP. Nie podoba mi się.", "13", "1")
INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2005-04-15 14:12:43", "Niestety dostaliśmy zwrotkę od testingu, więc nie ma się co śmiać - inne taski będą musiały poczekać. Sfołarduj mi tego meila, bo nasze dizajny niestety są bez polotu – jak zwykle, także czekać nas będą ostre konsekwencje. Straszny szejm, bo klient przesunął dedlajn na wczoraj, dlatego musi to być loł badżet.", "15", "2")
INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2013-04-23 12:16:00", "Może po pracy jakieś piwko na starówce? Odbierz ten fakin telefon! Pewnie ma przyjść trzech nowych deweloperów do timu. Tak myślę, że nawet ASAP wam nie pomoże, także proponuję wyjście na piwko po pracy. Dobrze, że nie ma już żadnych bagów, więc klient będzie usytasy. Nie wszystko musi być z sensem.", "18", "5")
INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2013-04-23 14:11:43", "Pracujesz jeszcze w innych dizajnach? I właśnie dlatego dizajn musi urywać jaja, także nie ma czasu na smęty. Chcesz urlop? W sezonie? O nie… odpalaj kompa i nie marudź, ale jak coś to wiesz, z twoim podejściem to nawet jako woźnego cię nigdzie nie zatrudnią, więc się ciesz, że masz pracę.", "17", "4")
INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2013-06-15 08:12:23", "Wygląda na to, że słabo wam ostatnio czelendże wychodzą, dlatego macie teraz zakaz wychodzenia na kawkę w czasie mitingów. Nie o to chodziło. Wiem, że jesteśmy wszyscy zawaleni robotą, ale menedżment nie jest naszą mocną stroną, dlatego musi to być loł badżet. Jutro mam hołmofisa. Jutro mamy apojtment, a żaden dizajn się nie spodobał, więc musisz zrobić risercz.", "11", "2")
INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2013-06-15 08:11:43", "Ciężka sprawa, bo i to jest priorytetowa sprawa, także kawusia jest w tej chwili najimportantniejsza. Bo w życiu chodzi o to, żeby czelendżować na maksa. Tak myślę, że słabo wam ostatnio czelendże wychodzą, więc czas na nowy czelendż. Uwaga! Brancz? Mamy info od koordynatora – nie ma już żadnych bagów, więc przeniosą mnie pewnie do innego projektu.", "9", "2")
INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2012-04-15 14:12:43", "Zapomnij o przerwie na lancz – znowu zmienili hasła do drukarek, ale co tam – nie płacą nam za nadgodziny. Tak czy inaczej, musicie zostać after ałers. Jutro łorkuję z domu, także się wdzwonię. Na to wygląda, że przed chwilą zapdejtowali gajdlajnsy, a Weronika ma jutro miting w tej sprawie, więc do roboty! Chodzą ploty, że trzeba to ASAP.", "9", "1")
INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2012-08-15 23:51:43", "Mamy info od koordynatora – mamy wszystkie konieczne apruwale, także piłeczka jest teraz po ich stronie. Łejt! Chyba ostatnio mieliście spadek formy, dlatego potrzeba wam porządnego kołczowania. Pracujesz jeszcze w innych dizajnach? W takim wypadku szykują się zwolnienia. O, jaki… wyłącz te głupie gify z kotami, ale wiesz, uśmiechnij się, najbliższe podwyżki planujemy za 5 lat!", "8", "6")
INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2013-07-02 23:23:43", "O, jaki… wyłącz te głupie gify z kotami, ale wiesz, każdy sam sobie wybiera gdzie mieszka i gdzie pracuje. Dodaj menedżera do FW. I co się dziwisz? Na to wygląda, że serwer się zaciął, a Anita ma jutro miting w tej sprawie, więc widzimy się na standapie za kwadrans. Podobno dostaliśmy zwrotkę od testingu, więc inne taski będą musiały poczekać.", "7", "6")
INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2013-04-04 11:08:43", "Spójrz na to z innej strony. Podobno dostaliśmy zwrotkę od testingu, więc nie ma się co śmiać - pamiętaj, że to teraz najimportantniejszy projekt. Jes! Dizajn musi urywać dupę, ale zbliża się dedlajn, więc nie ma czasu na kawki i pogaduchy. Chcesz urlop? W sezonie? O nie… zamykaj tego fejsa i siedź cicho, ale wiesz, zawsze możesz złożyć wymówienie.", "12", "6")
INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2013-07-12 14:11:51", "Zresztą tim lider i tak powiedział, że nie będzie premii. Wygląda na to, że nie potraficie ogarnąć nawet najprostszego fakapu, dlatego proponuję wyjście na piwko po pracy. Trzeba zrobić szybki risercz, musimy zrobić nowy dizajn, więc trzeba obrać nowy target. Po długich tygodniach ciężkiej pracy mamy wszystkie konieczne apruwale, więc sprawa jest jasna: klient będzie usytasy.", "12", "2")
INSERT INTO comments (created, text, tweet_id, user_id) VALUES ("2013-07-12 14:12:43", "Art dajrektor kazał przekazać, że klient odrzucił wszystkie ajdije, dlatego trzeba zapdejtować gajdlajnsy. Kto idzie na brejnstorm? Zapomnij o przerwie na kawkę, bo wiesz… czlendż jest taki pasjonujący, także fakap. Najwyżej w przyszłym miesiącu szykuje się impreza firmowa. Wiem, że masz już dużo na głowie, ale znowu zmienili hasła do drukarek, więc musisz zrobić mały risercz.", "12", "2")


